# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .greeter import *
from .provider import *
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "greeting",
  "mod": "index",
  "fqn": "pulumi_greeting",
  "classes": {
   "greeting:index:Greeter": "Greeter"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "greeting",
  "token": "pulumi:providers:greeting",
  "fqn": "pulumi_greeting",
  "class": "Provider"
 }
]
"""
)
