// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package greeting

import (
	"context"
	"reflect"

	"errors"
	"github.com/demo/greeting/sdk/go/greeting/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A greeter resource.
type Greeter struct {
	pulumi.ResourceState

	// The rendered greeting.
	Message pulumi.StringOutput `pulumi:"message"`
}

// NewGreeter registers a new resource with the given unique name, arguments, and options.
func NewGreeter(ctx *pulumi.Context,
	name string, args *GreeterArgs, opts ...pulumi.ResourceOption) (*Greeter, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Name == nil {
		return nil, errors.New("invalid value for required argument 'Name'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Greeter
	err := ctx.RegisterRemoteComponentResource("greeting:index:Greeter", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type greeterArgs struct {
	// Who to greet.
	Name string `pulumi:"name"`
}

// The set of arguments for constructing a Greeter resource.
type GreeterArgs struct {
	// Who to greet.
	Name pulumi.StringInput
}

func (GreeterArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*greeterArgs)(nil)).Elem()
}

type GreeterInput interface {
	pulumi.Input

	ToGreeterOutput() GreeterOutput
	ToGreeterOutputWithContext(ctx context.Context) GreeterOutput
}

func (*Greeter) ElementType() reflect.Type {
	return reflect.TypeOf((**Greeter)(nil)).Elem()
}

func (i *Greeter) ToGreeterOutput() GreeterOutput {
	return i.ToGreeterOutputWithContext(context.Background())
}

func (i *Greeter) ToGreeterOutputWithContext(ctx context.Context) GreeterOutput {
	return pulumi.ToOutputWithContext(ctx, i).(GreeterOutput)
}

type GreeterOutput struct{ *pulumi.OutputState }

func (GreeterOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Greeter)(nil)).Elem()
}

func (o GreeterOutput) ToGreeterOutput() GreeterOutput {
	return o
}

func (o GreeterOutput) ToGreeterOutputWithContext(ctx context.Context) GreeterOutput {
	return o
}

// The rendered greeting.
func (o GreeterOutput) Message() pulumi.StringOutput {
	return o.ApplyT(func(v *Greeter) pulumi.StringOutput { return v.Message }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*GreeterInput)(nil)).Elem(), &Greeter{})
	pulumi.RegisterOutputType(GreeterOutput{})
}
